spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: metadata-db-manager-service
  neo4j:
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
    uri: ${NEO4J_URI}
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka