server:
  port: 8083

spring:
  application:
    name: resource-manager-service
  cloud:
    discovery:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true

minio:
  url: http://minio-db:9000
  username: minio
  password: miniominio

metadata-db:
  url: lb://metadata-db-manager-service
  name: metadata-db-manager-service

eureka:
  client:
    service-url:
        defaultZone: http://discovery-service:8761/eureka
