server:
  port: 8080

spring:
  application:
    name: resource-manager
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    service:
      url:
        defaultZone: http://localhost:8761/eureka