server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: authentification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    password: oumaima
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


