spring:
  cloud:
    gateway:
      routes:
      - id: r1
        uri: http://lb:RESOURCE-MANAGER/
        predicates :
          - Path= /buckets/**,/resource/**
      - id : r2
        uri: http://lb:AUTHENTIFICATION-SERVICE/
        predicates:
          - Path= /api/v1/registration/**
      - id : r3
        uri: http://lb:DATABASE-MANAGER/
        predicates:
          - Path= /res/**,/users/**
