spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            maxAge: 3600
            allowCredentials: true
            allowedHeaders:
              - Origin
              - Content-type
              - Access-Control-Allow-Origin
              - Accept
              - responseType
              - Authorization
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT


server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
