version: '3.3'
services:
  minio-db:
    container_name: minio-db
    image: quay.io/minio/minio:latest
    command: server --console-address ":9090" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - $HOME/minio/data:/data
    ports:
      - "9000:9000"
      - "9090:9090"

  resource-service:
    image: resource-manager-service
    container_name: resource-manager-service
    ports:
      - "8083:8083"
    environment:
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}

  metadata-db-manager-service:
    container_name: metadata-db-manager-service
    image: schrodingdong/nexhub-metadata-db-manager-service
    ports:
      - "8082:8082"
    environment:
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: viTqWS71H4PyD-t1T3uZpU8PfarCXMVlsU8OIQxnBl8
      NEO4J_URI: neo4j+s://54d52f8a.databases.neo4j.io
