# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Nexhub CICD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-nexhub-discovery-service:
    runs-on: ubuntu-latest
    steps:
    - name: Github Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: cd to microservice directory
      run: cd ./microservices/discovery-service
    - name: build nexhub-discovery-service
      run: mvn package -DskipTests
  build-nexhub-gateway-service:
    runs-on: ubuntu-latest
    steps:
    - name: Github Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: cd to microservice directory
      run: cd ./microservices/gateway-service
    - name: build nexhub-gateway-service
      run: mvn package -DskipTests
  build-nexhub-resource-manager-service:
    runs-on: ubuntu-latest
    steps:
    - name: Github Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: cd to microservice directory
      run: cd ./microservices/resource-manager
    - name: build nexhub-resource-manager-service
      run: mvn package -DskipTests
  build-nexhub-metadata-db-manager-service:
    runs-on: ubuntu-latest
    steps:
    - name: Github Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: cd to microservice directory
      run: cd ./microservices/database-manager
    - name: build nexhub-metadata-db-manager-service
      run: mvn package -DskipTests
  build-nexhub-authentication-service:
    runs-on: ubuntu-latest
    steps:
    - name: Github Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: cd to microservice directory
      run: cd ./microservices/authentification
    - name: build nexhub-authentication-service
      run: mvn package -DskipTests
    
